FROM postgres:latest

# Used to seed the database while testing
ENV PGPASSWORD=password
RUN mkdir /pgsql
COPY . /pgsql
WORKDIR /pgsql
CMD ["psql",  "-h", "localhost", "-U", "postgres", "-f", "pg_dump.sql", "-w"]
