FROM postgres:latest

# Used to seed the database while testing

# ENV PGPASSWORD=password
# RUN mkdir /pgsql
# COPY . /pgsql
# WORKDIR /pgsql
# CMD ["psql",  "-h", "127.0.0.1", "-U", "postgres", "-f", "pg_dump.sql", "-w"]
